language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install requests
  - pip install -r requirements.txt
  - pip install -r testing-requirements.txt
# command to run tests
script: coverage run runtests.py
cache: pip
after_success:
  coveralls
